window.PRODUCT_CATALOG = [
  {
    sku: "PEP-PEPSI-12PK-12OZ",
    upcs: [],
    brand: "Pepsi",
    name: "Pepsi 12pk 12oz Cans",
    category: "Cola",
    package: "12pk / 12oz cans",
    salesChannel: "Shelf multipack",
    ownership: "PepsiCo owned",
    imageUrl: "assets/products/pepsi-12pk.jpg",
    imageStatus: "Local product image loaded",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-PEPSI-12OZ-CAN",
    upcs: ["01201303", "012000000133"],
    brand: "Pepsi",
    name: "Pepsi 12oz Can",
    category: "Cola",
    package: "12oz single can",
    salesChannel: "Single can reference",
    ownership: "PepsiCo owned",
    imageUrl: "assets/products/pepsi-12oz-can.png",
    imageStatus: "Prototype photo from field-captured Pepsi 12oz can barcode image",
    dataStatus: "Photo-captured UPC-E 01201303; expanded UPC-A 012000000133 - verify with PepsiCo master data"
  },
  {
    sku: "PEP-DIET-PEPSI-12PK-12OZ",
    upcs: ["012000809958"],
    brand: "Diet Pepsi",
    name: "Diet Pepsi 12pk 12oz Cans",
    category: "Cola",
    package: "12pk / 12oz cans",
    salesChannel: "Shelf multipack",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "UPC seeded from UPCItemDB - verify with PepsiCo master data"
  },
  {
    sku: "PEP-PEPSI-2L",
    upcs: [],
    brand: "Pepsi",
    name: "Pepsi 2 Liter Bottle",
    category: "Cola",
    package: "2L bottle",
    salesChannel: "Shelf bottle",
    ownership: "PepsiCo owned",
    imageUrl: "assets/products/pepsi-2l.jpg",
    imageStatus: "Local product image loaded",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-PEPSI-ZERO-12PK-12OZ",
    upcs: ["012000018794"],
    brand: "Pepsi Zero Sugar",
    name: "Pepsi Zero Sugar 12pk 12oz Cans",
    category: "Cola",
    package: "12pk / 12oz cans",
    salesChannel: "Shelf multipack",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "UPC seeded from UPCItemDB - verify with PepsiCo master data"
  },
  {
    sku: "PEP-WILD-CHERRY-12PK-12OZ",
    upcs: ["012000809996"],
    brand: "Pepsi Wild Cherry",
    name: "Pepsi Wild Cherry 12pk 12oz Cans",
    category: "Cola",
    package: "12pk / 12oz cans",
    salesChannel: "Shelf multipack",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "UPC seeded from UPCItemDB - verify with PepsiCo master data"
  },
  {
    sku: "PEP-PEPSI-20OZ",
    upcs: ["012000001291", "012000002946"],
    brand: "Pepsi",
    name: "Pepsi 20oz Bottle",
    category: "Cola",
    package: "20oz bottle",
    salesChannel: "Cooler single",
    ownership: "PepsiCo owned",
    imageUrl: "https://smartlabel.pepsico.info/012000001291-0013-en-US/images/b86c05bf-2a5b-4777-bc98-a58b72101625.jpg",
    imageStatus: "Official SmartLabel product image URL - verify final SKU art with PepsiCo master data",
    dataStatus: "SmartLabel UPC plus UPCItemDB seed - verify with PepsiCo master data"
  },
  {
    sku: "PEP-MTDEW-12PK-12OZ",
    upcs: [],
    brand: "Mountain Dew",
    name: "Mountain Dew 12pk 12oz Cans",
    category: "Citrus soda",
    package: "12pk / 12oz cans",
    salesChannel: "Shelf multipack",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-MTDEW-CODERED-12PK-12OZ",
    upcs: [],
    brand: "Mountain Dew Code Red",
    name: "Mountain Dew Code Red 12pk 12oz Cans",
    category: "Citrus soda",
    package: "12pk / 12oz cans",
    salesChannel: "Shelf multipack",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-MTDEW-20OZ",
    upcs: [],
    brand: "Mountain Dew",
    name: "Mountain Dew 20oz Bottle",
    category: "Citrus soda",
    package: "20oz bottle",
    salesChannel: "Cooler single",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-MTDEW-2L",
    upcs: [],
    brand: "Mountain Dew",
    name: "Mountain Dew 2 Liter Bottle",
    category: "Citrus soda",
    package: "2L bottle",
    salesChannel: "Shelf bottle",
    ownership: "PepsiCo owned",
    imageUrl: "assets/products/mountain-dew-2l.jpg",
    imageStatus: "Local product image loaded",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-STARRY-12PK-12OZ",
    upcs: [],
    brand: "Starry",
    name: "Starry Lemon Lime 12pk 12oz Cans",
    category: "Lemon-lime soda",
    package: "12pk / 12oz cans",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-MUG-12PK-12OZ",
    upcs: [],
    brand: "Mug",
    name: "Mug Root Beer 12pk 12oz Cans",
    category: "Root beer",
    package: "12pk / 12oz cans",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-CRUSH-ORANGE-12PK-12OZ",
    upcs: [],
    brand: "Crush",
    name: "Crush Orange 12pk 12oz Cans",
    category: "Flavored soda",
    package: "12pk / 12oz cans",
    ownership: "Territory-dependent",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-POPPI-STRAW-LEMON-12OZ",
    upcs: [],
    brand: "Poppi",
    name: "Poppi Strawberry Lemon 12oz Can",
    category: "Functional soda",
    package: "12oz can",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-POPPI-CLASSIC-COLA-12OZ",
    upcs: [],
    brand: "Poppi",
    name: "Poppi Classic Cola 12oz Can",
    category: "Functional soda",
    package: "12oz can",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-GAT-28OZ-GLACIER-FREEZE",
    upcs: [],
    brand: "Gatorade",
    name: "Gatorade 28oz Glacier Freeze",
    category: "Sports drink",
    package: "28oz bottle",
    ownership: "PepsiCo owned",
    imageUrl: "assets/products/gatorade-glacier-freeze-28oz.jpg",
    imageStatus: "Local product image loaded",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-GAT-28OZ-FRUIT-PUNCH",
    upcs: [],
    brand: "Gatorade",
    name: "Gatorade 28oz Fruit Punch",
    category: "Sports drink",
    package: "28oz bottle",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-GAT-ZERO-28OZ-GLACIER-CHERRY",
    upcs: [],
    brand: "Gatorade Zero",
    name: "Gatorade Zero 28oz Glacier Cherry",
    category: "Sports drink",
    package: "28oz bottle",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-GAT-12PK-VARIETY",
    upcs: [],
    brand: "Gatorade",
    name: "Gatorade 12pk Variety",
    category: "Sports drink",
    package: "12pk bottles",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-GATORLYTE-20OZ-CHERRY-LIME",
    upcs: [],
    brand: "Gatorlyte",
    name: "Gatorlyte 20oz Cherry Lime",
    category: "Electrolyte drink",
    package: "20oz bottle",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-FAST-TWITCH-12OZ-ORANGE",
    upcs: [],
    brand: "Fast Twitch",
    name: "Fast Twitch 12oz Orange",
    category: "Energy / sports",
    package: "12oz bottle",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-AQUAFINA-24PK-16-9OZ",
    upcs: [],
    brand: "Aquafina",
    name: "Aquafina 24pk 16.9oz Bottles",
    category: "Water",
    package: "24pk / 16.9oz bottles",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-LIFEWTR-1L",
    upcs: [],
    brand: "LIFEWTR",
    name: "LIFEWTR 1L Bottle",
    category: "Water",
    package: "1L bottle",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-PROPEL-BERRY-6PK",
    upcs: [],
    brand: "Propel",
    name: "Propel Berry 6pk",
    category: "Enhanced water",
    package: "6pk bottles",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-BUBLY-LIME-8PK",
    upcs: [],
    brand: "bubly",
    name: "bubly Lime 8pk 12oz Cans",
    category: "Sparkling water",
    package: "8pk / 12oz cans",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-CELSIUS-SPARKLING-ORANGE-12OZ",
    upcs: [],
    brand: "Celsius",
    name: "Celsius Sparkling Orange 12oz Can",
    category: "Energy",
    package: "12oz can",
    ownership: "PepsiCo distributed / strategic partner",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-ALANI-NU-CHERRY-SLUSH-12OZ",
    upcs: [],
    brand: "Alani Nu",
    name: "Alani Nu Cherry Slush 12oz Can",
    category: "Energy",
    package: "12oz can",
    ownership: "PepsiCo distributed / Celsius-owned",
    imageUrl: "assets/products/alani-cherry-slush.png",
    imageStatus: "Local product image loaded",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-ROCKSTAR-ORIGINAL-16OZ",
    upcs: [],
    brand: "Rockstar",
    name: "Rockstar Original 16oz Can",
    category: "Energy",
    package: "16oz can",
    ownership: "PepsiCo/Celsius territory-dependent",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-AMP-ORIGINAL-16OZ",
    upcs: [],
    brand: "AMP",
    name: "AMP Original 16oz Can",
    category: "Energy",
    package: "16oz can",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-PURE-LEAF-SWEET-18-5OZ",
    upcs: [],
    brand: "Pure Leaf",
    name: "Pure Leaf Sweet Tea 18.5oz Bottle",
    category: "Tea",
    package: "18.5oz bottle",
    ownership: "PepsiCo/Unilever partnership",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-BRISK-LEMON-1L",
    upcs: [],
    brand: "Brisk",
    name: "Brisk Lemon Iced Tea 1L",
    category: "Tea",
    package: "1L bottle",
    ownership: "PepsiCo/Unilever partnership",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-STARBUCKS-FRAP-MOCHA-13-7OZ",
    upcs: [],
    brand: "Starbucks RTD",
    name: "Starbucks Frappuccino Mocha 13.7oz Bottle",
    category: "Coffee",
    package: "13.7oz bottle",
    ownership: "PepsiCo/Starbucks partnership",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-TROPICANA-OJ-52OZ",
    upcs: [],
    brand: "Tropicana",
    name: "Tropicana Pure Premium Orange Juice 52oz",
    category: "Juice",
    package: "52oz bottle",
    ownership: "Tropicana Brands Group / PepsiCo distribution",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-NAKED-GREEN-MACHINE-15-2OZ",
    upcs: [],
    brand: "Naked",
    name: "Naked Green Machine 15.2oz Bottle",
    category: "Juice / smoothie",
    package: "15.2oz bottle",
    ownership: "Tropicana Brands Group / PepsiCo distribution",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  },
  {
    sku: "PEP-KEVITA-GINGER-LEMON-15-2OZ",
    upcs: [],
    brand: "KeVita",
    name: "KeVita Ginger Lemon 15.2oz Bottle",
    category: "Functional probiotic",
    package: "15.2oz bottle",
    ownership: "PepsiCo owned",
    imageUrl: "",
    imageStatus: "Needs official product image",
    dataStatus: "SKU shell - UPC pending"
  }
];
